spring:
  application:
    name: srm-test


  data:
    mongodb:
      host: localhost
      port: 27017
      database: myDb



reqres:
  api:
    url: https://reqres.in/api/users/{id}
    apiKeyValue: reqres-free-v1
